name: CI tests

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm run build
      - run: npm run zip
      - name: Upload dist zip file
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip

  terraform:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials from Test account

        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/checkout@v2
      - name: Download dist result from build
        uses: actions/download-artifact@v2
        with:
          name: dist

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Terraform fmt
        id: fmt
        run: cd .. && ls -la

        working-directory: ./terraform

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform

      - name: Terraform apply
        if: github.ref == 'refs/heads/master'
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
